name: KICS IaC Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  kics-scan:
    name: KICS Infrastructure Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Results Directory
        run: mkdir -p kics-results

      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@v2.1.14
        with:
          # Scan paths - targeting IaC files in NodeGoat
          path: 'Dockerfile,docker-compose.yml,config'
          
          # Output configuration
          output_path: kics-results
          output_formats: 'json,sarif,html'
          
          # Platform types to scan - FIXED: Changed 'Docker' to 'DockerCompose'
          platform_type: 'Dockerfile,DockerCompose'
          
          # Fail on specific severities
          fail_on: 'high,medium'
          ignore_on_exit: 'none'
          
          # Enable PR comments for better visibility
          enable_comments: true
          enable_jobs_summary: true
          enable_annotations: true
          comments_with_queries: true
          
          # Token for PR comments
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Exclude paths that don't need scanning
          exclude_paths: 'node_modules/**,kics-results/**,.git/**'
          
          # Verbose output for detailed logs
          verbose: true
          
          # Timeout (seconds)
          timeout: 120

      - name: Display KICS Results Summary
        if: always()
        run: |
          echo "📊 KICS Scan Completed!"
          echo "================================"
          if [ -f kics-results/results.json ]; then
            echo "✅ Results file generated"
            echo ""
            echo "📈 Quick Stats:"
            cat kics-results/results.json | jq -r '
              "Total Issues: \(.total_counter // 0)",
              "High: \(.severity_counters.HIGH // 0)",
              "Medium: \(.severity_counters.MEDIUM // 0)",
              "Low: \(.severity_counters.LOW // 0)",
              "Info: \(.severity_counters.INFO // 0)"
            '
          else
            echo "⚠️  No results file found"
          fi

      - name: Upload KICS Results as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kics-scan-results
          path: kics-results/
          retention-days: 30

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kics-results/results.sarif
          category: kics-iac-scan

      - name: Comment PR with HTML Report Link
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            if (fs.existsSync('kics-results/results.html')) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '📊 **KICS Infrastructure Scan Complete!**\n\n' +
                      'Download the detailed HTML report from the workflow artifacts section.'
              });
            }